# -*- coding: utf-8 -*-
"""comparison_algos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYF6P9Q7aeAzCXGh_Q_AYRVP38_Oe69Z
"""

# SdAE
# =========================================================
# SdAE (Stacked Denoising AutoEncoder) BASELINE – FULL CODE
# Predict next month y_{t+1} using features at month t
# Split by TARGET MONTH: train (1..23), val (24..29), test (30..35)
# Metrics: MAE, RMSE, MAPE, Accuracy@20, Recall@20, ZeroRate
# Output: month-wise metrics (all months), final test avg, best month
# GPU: works on T4 (cuda)
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import random

# =========================
# 0. SEEDS + DEVICE
# =========================
seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# =========================
# 1. LOAD DATA
# =========================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"], errors="coerce")
df = df.dropna(subset=["YEAR_MONTH"]).copy()
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

segments = sorted(df["SEGMENT_KEY"].unique())
months   = sorted(df["YEAR_MONTH"].unique())
N = len(segments)
T = len(months)
print("Segments:", N, "Months:", T, "|", months[0], "->", months[-1])
assert T == 36, "Expected 36 months."

seg2idx = {s:i for i,s in enumerate(segments)}
mon2idx = {m:i for i,m in enumerate(months)}

# =========================
# 2. CHOOSE NUMERIC FEATURES
# =========================
# We will use ALL numeric variables except the target, plus a crash-history channel.
# Input at month t predicts target at month t+1.
numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in ["TOTAL_CRASHES", "YEAR_QUARTER", "YEAR_HALF"]
]

# Fill missing
df[numeric_cols] = df[numeric_cols].fillna(0.0)
df["TOTAL_CRASHES"] = df["TOTAL_CRASHES"].fillna(0.0)

F_num = len(numeric_cols)
F_dim = F_num + 1  # + crash history feature

# =========================
# 3. BUILD X (N,T,F) AND y (N,T)
# =========================
X = np.zeros((N, T, F_dim), dtype=np.float32)
y = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = mon2idx[r["YEAR_MONTH"]]
    X[i, t, :F_num] = r[numeric_cols].values.astype(np.float32)
    X[i, t, F_num]  = float(r["TOTAL_CRASHES"])   # crash history at month t
    y[i, t]         = float(r["TOTAL_CRASHES"])

# =========================
# 4. MAKE SUPERVISED PAIRS: (seg, month t) -> y_{t+1}
# Target months m = 1..35
# =========================
# For each target month m, input month is (m-1).
# We keep month index as the TARGET month index m (1..35) for month-wise metrics.

pairs_X = []
pairs_y = []
pairs_seg = []
pairs_m = []  # target month index m

for i in range(N):
    for m in range(1, T):  # 1..35
        pairs_X.append(X[i, m-1, :])
        pairs_y.append(y[i, m])
        pairs_seg.append(i)
        pairs_m.append(m)

pairs_X = np.asarray(pairs_X, dtype=np.float32)  # (N*(T-1), F)
pairs_y = np.asarray(pairs_y, dtype=np.float32)  # (N*(T-1),)
pairs_seg = np.asarray(pairs_seg, dtype=np.int32)
pairs_m = np.asarray(pairs_m, dtype=np.int32)

# =========================
# 5. SPLIT BY TARGET MONTH (NO FUTURE PEEK)
# train: m=1..23, val: 24..29, test: 30..35
# =========================
train_mask = (pairs_m >= 1)  & (pairs_m <= 23)
val_mask   = (pairs_m >= 24) & (pairs_m <= 29)
test_mask  = (pairs_m >= 30) & (pairs_m <= 35)

X_train, y_train = pairs_X[train_mask], pairs_y[train_mask]
X_val,   y_val   = pairs_X[val_mask],   pairs_y[val_mask]
X_test,  y_test  = pairs_X[test_mask],  pairs_y[test_mask]

seg_train, m_train = pairs_seg[train_mask], pairs_m[train_mask]
seg_val,   m_val   = pairs_seg[val_mask],   pairs_m[val_mask]
seg_test,  m_test  = pairs_seg[test_mask],  pairs_m[test_mask]

print("Samples | train:", len(X_train), "val:", len(X_val), "test:", len(X_test))

# =========================
# 6. STANDARDIZE FEATURES (FIT ON TRAIN ONLY)
# =========================
mu = X_train.mean(axis=0, keepdims=True)
sd = X_train.std(axis=0, keepdims=True) + 1e-6

def zscore(a):
    return (a - mu) / sd

X_train_s = zscore(X_train)
X_val_s   = zscore(X_val)
X_test_s  = zscore(X_test)

# =========================
# 7. DATASET + DATALOADER
# =========================
class PairDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X).float()
        self.y = torch.from_numpy(y).float().view(-1, 1)
    def __len__(self):
        return self.X.size(0)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

batch_size = 4096  # T4 friendly; reduce if OOM
train_loader = DataLoader(PairDataset(X_train_s, y_train), batch_size=batch_size, shuffle=True, drop_last=False)
val_loader   = DataLoader(PairDataset(X_val_s,   y_val),   batch_size=batch_size, shuffle=False, drop_last=False)

# =========================
# 8. SdAE MODEL (Denoising AE + Regressor)
# =========================
class SdAE(nn.Module):
    def __init__(self, in_dim, h1=256, h2=128, z=64, dropout=0.1):
        super().__init__()
        # Encoder
        self.enc = nn.Sequential(
            nn.Linear(in_dim, h1),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(h1, h2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(h2, z),
            nn.ReLU()
        )
        # Decoder (for AE pretrain)
        self.dec = nn.Sequential(
            nn.Linear(z, h2),
            nn.ReLU(),
            nn.Linear(h2, h1),
            nn.ReLU(),
            nn.Linear(h1, in_dim)
        )
        # Regression head
        self.reg = nn.Sequential(
            nn.Linear(z, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

    def encode(self, x):
        return self.enc(x)

    def reconstruct(self, x):
        z = self.encode(x)
        return self.dec(z)

    def forward(self, x):
        z = self.encode(x)
        out = self.reg(z)
        return F.softplus(out)  # ensure non-negative crash predictions

model = SdAE(in_dim=F_dim, h1=256, h2=128, z=64, dropout=0.1).to(device)

# =========================
# 9. DENOISING FUNCTION
# =========================
def add_noise(x, p_mask=0.15, sigma=0.05):
    # x: standardized features
    # masking noise + small gaussian noise
    if p_mask > 0:
        mask = (torch.rand_like(x) < p_mask).float()
        x = x * (1 - mask)
    if sigma > 0:
        x = x + sigma * torch.randn_like(x)
    return x

# =========================
# 10. STAGE 1: AE PRETRAIN (FAST)
# =========================
ae_epochs = 10
ae_opt = torch.optim.Adam(list(model.enc.parameters()) + list(model.dec.parameters()), lr=1e-3)

best_ae = float("inf")
best_ae_state = None
patience = 3
bad = 0

for epoch in range(1, ae_epochs + 1):
    model.train()
    tr_losses = []
    for xb, _ in train_loader:
        xb = xb.to(device)
        xb_noisy = add_noise(xb, p_mask=0.15, sigma=0.05)

        recon = model.reconstruct(xb_noisy)
        loss = F.mse_loss(recon, xb)

        ae_opt.zero_grad()
        loss.backward()
        ae_opt.step()

        tr_losses.append(loss.item())

    model.eval()
    with torch.no_grad():
        va_losses = []
        for xb, _ in val_loader:
            xb = xb.to(device)
            xb_noisy = add_noise(xb, p_mask=0.15, sigma=0.05)
            recon = model.reconstruct(xb_noisy)
            va_losses.append(F.mse_loss(recon, xb).item())
        val_loss = float(np.mean(va_losses))

    print(f"[AE] Epoch {epoch:02d} | TrainRecon={np.mean(tr_losses):.6f} | ValRecon={val_loss:.6f}")

    if val_loss < best_ae - 1e-6:
        best_ae = val_loss
        best_ae_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        bad = 0
    else:
        bad += 1
        if bad >= patience:
            print(f"[AE] Early stop at epoch {epoch:02d} | Best ValRecon={best_ae:.6f}")
            break

if best_ae_state is not None:
    model.load_state_dict(best_ae_state)

# =========================
# 11. STAGE 2: REGRESSION FINETUNE (ENCODER + REG HEAD)
# =========================
reg_epochs = 20
opt = torch.optim.Adam(list(model.enc.parameters()) + list(model.reg.parameters()), lr=1e-3)

best_val = float("inf")
best_state = None
bad = 0
patience = 4

for epoch in range(1, reg_epochs + 1):
    model.train()
    tr_losses = []
    for xb, yb in train_loader:
        xb = xb.to(device)
        yb = yb.to(device)

        pred = model(xb)
        loss = F.mse_loss(pred, yb)

        opt.zero_grad()
        loss.backward()
        opt.step()
        tr_losses.append(loss.item())

    model.eval()
    with torch.no_grad():
        va_losses = []
        for xb, yb in val_loader:
            xb = xb.to(device)
            yb = yb.to(device)
            pred = model(xb)
            va_losses.append(F.mse_loss(pred, yb).item())
        val_loss = float(np.mean(va_losses))

    print(f"[REG] Epoch {epoch:02d} | TrainMSE={np.mean(tr_losses):.6f} | ValMSE={val_loss:.6f}")

    if val_loss < best_val - 1e-6:
        best_val = val_loss
        best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        bad = 0
    else:
        bad += 1
        if bad >= patience:
            print(f"[REG] Early stop at epoch {epoch:02d} | Best ValMSE={best_val:.6f}")
            break

if best_state is not None:
    model.load_state_dict(best_state)

save_path = "/content/drive/MyDrive/Upstream/sdae_houston_36month.pth"
torch.save(model.state_dict(), save_path)
print("Saved SdAE:", save_path)

# =========================
# 12. METRIC FUNCTIONS (MONTH-WISE)
# =========================
def MAE(yt, yp):
    return float(np.mean(np.abs(yt - yp)))

def RMSE(yt, yp):
    return float(np.sqrt(np.mean((yt - yp) ** 2)))

def MAPE(yt, yp, eps=1e-6):
    return float(np.mean(np.abs((yt - yp) / np.maximum(yt, eps))))

def AccHR20(yt, yp):
    denom = np.sum(yt > 0)
    if denom == 0:
        return np.nan
    thr = np.quantile(yp, 0.8)
    return float(np.sum((yt > 0) & (yp >= thr)) / denom)

def Recall20(yt, yp):
    Nn = yt.shape[0]
    K = max(1, int(0.2 * Nn))
    top_true = np.argsort(-yt)[:K]
    top_pred = np.argsort(-yp)[:K]
    return float(len(set(top_true) & set(top_pred)) / K)

def ZeroRate(yp):
    return float(np.mean(yp < 1e-6))

# =========================
# 13. PREDICT FOR ALL MONTHS (m=1..35) AND COMPUTE MONTH-WISE METRICS
# =========================
# We will predict using the paired inputs we already built (pairs_X),
# then place predictions into (N, 35) array by (segment, target_month m).

model.eval()

# Predict all pairs in one go (batched)
all_X_s = zscore(pairs_X).astype(np.float32)
all_pred = np.zeros((all_X_s.shape[0],), dtype=np.float32)

with torch.no_grad():
    bs = 65536
    for start in range(0, all_X_s.shape[0], bs):
        end = min(start + bs, all_X_s.shape[0])
        xb = torch.from_numpy(all_X_s[start:end]).to(device)
        pb = model(xb).squeeze(-1).detach().cpu().numpy().astype(np.float32)
        all_pred[start:end] = pb

# Fill segment × month prediction matrix (months 1..35)
y_pred_sdae = np.zeros((N, T-1), dtype=np.float32)  # (N,35)

for k in range(all_pred.shape[0]):
    i = pairs_seg[k]
    m = pairs_m[k]          # 1..35
    y_pred_sdae[i, m-1] = all_pred[k]

# Month-wise metrics for ALL months (prediction months 1..35)
rows = []
for m in range(1, T):  # 1..35
    yt = y[:, m]           # actual at target month m
    yp = y_pred_sdae[:, m-1]

    rows.append({
        "YEAR_MONTH": months[m],
        "MONTH_INDEX": m,
        "MAE": MAE(yt, yp),
        "RMSE": RMSE(yt, yp),
        "MAPE": MAPE(yt, yp),
        "Accuracy@20": AccHR20(yt, yp),
        "Recall@20": Recall20(yt, yp),
        "ZeroRate": ZeroRate(yp),
        "SPLIT": ("TRAIN" if m <= 23 else ("VAL" if m <= 29 else "TEST"))
    })

sdae_monthly_df = pd.DataFrame(rows)

print("\nPreview month-wise metrics:")
print(sdae_monthly_df.head(10))

# =========================
# 14. FINAL TEST METRICS (AVG OVER TEST MONTHS)
# =========================
test_df = sdae_monthly_df[sdae_monthly_df["SPLIT"] == "TEST"]

final_metrics = {
    "MAE": test_df["MAE"].mean(),
    "RMSE": test_df["RMSE"].mean(),
    "MAPE": test_df["MAPE"].mean(),
    "Accuracy@20": test_df["Accuracy@20"].mean(),
    "Recall@20": test_df["Recall@20"].mean(),
    "ZeroRate": test_df["ZeroRate"].mean(),
}

print("\n===== FINAL SdAE METRICS (TEST AVG) =====")
for k, v in final_metrics.items():
    print(f"{k:12s}: {v:.6f}")

# =========================
# 15. BEST PERFORMING MONTH (BY MAE) + ALL VALUES
# =========================
best_row = sdae_monthly_df.loc[sdae_monthly_df["MAE"].idxmin()]

print("\n===== BEST PERFORMING MONTH (SdAE) =====")
for col in best_row.index:
    print(f"{col:14s}: {best_row[col]}")

# =========================
# 16. SAVE OUTPUTS
# =========================
metrics_path = "/content/drive/MyDrive/Upstream/SdAE_monthwise_metrics_36months.csv"
sdae_monthly_df.to_csv(metrics_path, index=False)
print("\nSaved month-wise metrics:", metrics_path)

# Optional: save per-segment month-wise predictions (N × 35) as CSV (wide)
pred_wide = pd.DataFrame(y_pred_sdae, columns=[months[m].strftime("%Y-%m") for m in range(1, T)])
pred_wide.insert(0, "SEGMENT_KEY", segments)

pred_path = "/content/drive/MyDrive/Upstream/SdAE_predictions_segment_by_month.csv"
pred_wide.to_csv(pred_path, index=False)
print("Saved predictions:", pred_path)

# TARPM-L
# =========================================================
# TARPM-L (Time-Aware Linear Regression) BASELINE
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

# =========================================================
# 1. LOAD DATA
# =========================================================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"])
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

segments = sorted(df["SEGMENT_KEY"].unique())
months   = sorted(df["YEAR_MONTH"].unique())

seg2idx = {s:i for i,s in enumerate(segments)}
mon2idx = {m:i for i,m in enumerate(months)}

N = len(segments)
T = len(months)
assert T == 36

# =========================================================
# 2. NUMERIC FEATURES
# =========================================================
numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in ["TOTAL_CRASHES", "YEAR_QUARTER", "YEAR_HALF"]
]

df[numeric_cols] = df[numeric_cols].fillna(0.0)
df["TOTAL_CRASHES"] = df["TOTAL_CRASHES"].fillna(0.0)

# =========================================================
# 3. BUILD (SEGMENT × MONTH) MATRICES
# =========================================================
F_num = len(numeric_cols)

X_full = np.zeros((N, T, F_num), dtype=np.float32)
y_full = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = mon2idx[r["YEAR_MONTH"]]
    X_full[i, t, :] = r[numeric_cols].values
    y_full[i, t]    = r["TOTAL_CRASHES"]

# =========================================================
# 4. BUILD TIME-AWARE SUPERVISED DATA
# Input month = m-1
# Target month = m
# Lags: y_{m-1}, y_{m-2}, y_{m-3}
# =========================================================
X_rows, y_rows, m_rows = [], [], []

for i in range(N):
    for m in range(3, T):  # start at m=3 to have 3 lags
        x_feat = X_full[i, m-1, :]
        lags = [
            y_full[i, m-1],
            y_full[i, m-2],
            y_full[i, m-3]
        ]
        X_rows.append(np.hstack([x_feat, lags]))
        y_rows.append(y_full[i, m])
        m_rows.append(m)

X_rows = np.asarray(X_rows, dtype=np.float32)
y_rows = np.asarray(y_rows, dtype=np.float32)
m_rows = np.asarray(m_rows, dtype=np.int32)

# =========================================================
# 5. SPLIT (NO FUTURE PEEK)
# =========================================================
train_mask = (m_rows >= 3)  & (m_rows <= 23)
val_mask   = (m_rows >= 24) & (m_rows <= 29)
test_mask  = (m_rows >= 30) & (m_rows <= 35)

X_train, y_train = X_rows[train_mask], y_rows[train_mask]
X_val,   y_val   = X_rows[val_mask],   y_rows[val_mask]
X_test,  y_test  = X_rows[test_mask],  y_rows[test_mask]

m_train = m_rows[train_mask]
m_val   = m_rows[val_mask]
m_test  = m_rows[test_mask]

# =========================================================
# 6. STANDARDIZE (FIT ON TRAIN)
# =========================================================
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_val_s   = scaler.transform(X_val)
X_test_s  = scaler.transform(X_test)

# =========================================================
# 7. TRAIN LINEAR MODEL
# =========================================================
model = LinearRegression()
model.fit(X_train_s, y_train)

# =========================================================
# 8. PREDICT ALL MONTHS (m=3..35)
# =========================================================
X_all_s = scaler.transform(X_rows)
y_pred_all = model.predict(X_all_s)
y_pred_all = np.maximum(y_pred_all, 0.0)

# Place into (N × 35) matrix
y_pred_tarpm = np.zeros((N, T-1), dtype=np.float32)

idx = 0
for i in range(N):
    for m in range(3, T):
        y_pred_tarpm[i, m-1] = y_pred_all[idx]
        idx += 1

# =========================================================
# 9. METRICS
# =========================================================
def MAE(yt, yp):
    return np.mean(np.abs(yt - yp))

def RMSE(yt, yp):
    return np.sqrt(np.mean((yt - yp)**2))

def MAPE(yt, yp, eps=1e-6):
    return np.mean(np.abs((yt - yp) / np.maximum(yt, eps)))

def AccHR20(yt, yp):
    denom = np.sum(yt > 0)
    if denom == 0:
        return np.nan
    thr = np.quantile(yp, 0.8)
    return np.sum((yt > 0) & (yp >= thr)) / denom

def Recall20(yt, yp):
    K = max(1, int(0.2 * len(yt)))
    return len(set(np.argsort(-yt)[:K]) & set(np.argsort(-yp)[:K])) / K

def ZeroRate(yp):
    return np.mean(yp < 1e-6)

# =========================================================
# 10. MONTH-WISE METRICS (ALL MONTHS)
# =========================================================
rows = []

for m in range(3, T):
    yt = y_full[:, m]
    yp = y_pred_tarpm[:, m-1]

    rows.append({
        "YEAR_MONTH": months[m],
        "MONTH_INDEX": m,
        "MAE": MAE(yt, yp),
        "RMSE": RMSE(yt, yp),
        "MAPE": MAPE(yt, yp),
        "Accuracy@20": AccHR20(yt, yp),
        "Recall@20": Recall20(yt, yp),
        "ZeroRate": ZeroRate(yp),
        "SPLIT": ("TRAIN" if m <= 23 else ("VAL" if m <= 29 else "TEST"))
    })

tarpm_df = pd.DataFrame(rows)

# =========================================================
# 11. FINAL TEST METRICS
# =========================================================
test_df = tarpm_df[tarpm_df["SPLIT"] == "TEST"]

print("\n===== FINAL TARPM-L METRICS (TEST AVG) =====")
for c in ["MAE", "RMSE", "MAPE", "Accuracy@20", "Recall@20", "ZeroRate"]:
    print(f"{c:12s}: {test_df[c].mean():.6f}")

# =========================================================
# 12. BEST PERFORMING MONTH
# =========================================================
best_row = tarpm_df.loc[tarpm_df["MAE"].idxmin()]

print("\n===== BEST PERFORMING MONTH (TARPM-L) =====")
for k, v in best_row.items():
    print(f"{k:14s}: {v}")

# =========================================================
# 13. SAVE
# =========================================================
out_path = "/content/drive/MyDrive/Upstream/TARPM-L_monthwise_metrics_36months.csv"
tarpm_df.to_csv(out_path, index=False)
print("\nSaved:", out_path)

# XGBOOST
# =========================================================
# XGBOOST BASELINE (Time-aware, tabular)
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler

# =========================================================
# 1. LOAD DATA
# =========================================================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"])
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

segments = sorted(df["SEGMENT_KEY"].unique())
months   = sorted(df["YEAR_MONTH"].unique())

seg2idx = {s:i for i,s in enumerate(segments)}
mon2idx = {m:i for i,m in enumerate(months)}

N = len(segments)
T = len(months)
assert T == 36

# =========================================================
# 2. NUMERIC FEATURES
# =========================================================
numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in ["TOTAL_CRASHES", "YEAR_QUARTER", "YEAR_HALF"]
]

df[numeric_cols] = df[numeric_cols].fillna(0.0)
df["TOTAL_CRASHES"] = df["TOTAL_CRASHES"].fillna(0.0)

# =========================================================
# 3. BUILD (SEGMENT × MONTH) MATRICES
# =========================================================
F_num = len(numeric_cols)

X_full = np.zeros((N, T, F_num), dtype=np.float32)
y_full = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = mon2idx[r["YEAR_MONTH"]]
    X_full[i, t, :] = r[numeric_cols].values
    y_full[i, t]    = r["TOTAL_CRASHES"]

# =========================================================
# 4. BUILD TIME-AWARE SUPERVISED DATA
# Input month = m-1
# Target month = m
# Lags: y_{m-1}, y_{m-2}, y_{m-3}
# =========================================================
X_rows, y_rows, m_rows = [], [], []

for i in range(N):
    for m in range(3, T):  # need 3 lags
        feats = X_full[i, m-1, :]
        lags  = [y_full[i, m-1], y_full[i, m-2], y_full[i, m-3]]
        X_rows.append(np.hstack([feats, lags]))
        y_rows.append(y_full[i, m])
        m_rows.append(m)

X_rows = np.asarray(X_rows, dtype=np.float32)
y_rows = np.asarray(y_rows, dtype=np.float32)
m_rows = np.asarray(m_rows, dtype=np.int32)

# =========================================================
# 5. SPLIT (NO FUTURE PEEK)
# =========================================================
train_mask = (m_rows >= 3)  & (m_rows <= 23)
val_mask   = (m_rows >= 24) & (m_rows <= 29)
test_mask  = (m_rows >= 30) & (m_rows <= 35)

X_train, y_train = X_rows[train_mask], y_rows[train_mask]
X_val,   y_val   = X_rows[val_mask],   y_rows[val_mask]
X_test,  y_test  = X_rows[test_mask],  y_rows[test_mask]

m_train = m_rows[train_mask]
m_val   = m_rows[val_mask]
m_test  = m_rows[test_mask]

# =========================================================
# 6. STANDARDIZE (TREE MODELS DON'T REQUIRE IT, BUT OK)
# =========================================================
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_val_s   = scaler.transform(X_val)
X_test_s  = scaler.transform(X_test)

# =========================================================
# 7. TRAIN XGBOOST
# =========================================================
model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train_s, y_train,
    eval_set=[(X_val_s, y_val)],
    verbose=False
)

# =========================================================
# 8. PREDICT ALL MONTHS (m=3..35)
# =========================================================
X_all_s = scaler.transform(X_rows)
y_pred_all = model.predict(X_all_s)
y_pred_all = np.maximum(y_pred_all, 0.0)

# Place into (N × 35)
y_pred_xgb = np.zeros((N, T-1), dtype=np.float32)

idx = 0
for i in range(N):
    for m in range(3, T):
        y_pred_xgb[i, m-1] = y_pred_all[idx]
        idx += 1

# =========================================================
# 9. METRICS
# =========================================================
def MAE(yt, yp):
    return np.mean(np.abs(yt - yp))

def RMSE(yt, yp):
    return np.sqrt(np.mean((yt - yp)**2))

def MAPE(yt, yp, eps=1e-6):
    return np.mean(np.abs((yt - yp) / np.maximum(yt, eps)))

def AccHR20(yt, yp):
    denom = np.sum(yt > 0)
    if denom == 0:
        return np.nan
    thr = np.quantile(yp, 0.8)
    return np.sum((yt > 0) & (yp >= thr)) / denom

def Recall20(yt, yp):
    K = max(1, int(0.2 * len(yt)))
    return len(set(np.argsort(-yt)[:K]) & set(np.argsort(-yp)[:K])) / K

def ZeroRate(yp):
    return np.mean(yp < 1e-6)

# =========================================================
# 10. MONTH-WISE METRICS (ALL MONTHS)
# =========================================================
rows = []

for m in range(3, T):
    yt = y_full[:, m]
    yp = y_pred_xgb[:, m-1]

    rows.append({
        "YEAR_MONTH": months[m],
        "MONTH_INDEX": m,
        "MAE": MAE(yt, yp),
        "RMSE": RMSE(yt, yp),
        "MAPE": MAPE(yt, yp),
        "Accuracy@20": AccHR20(yt, yp),
        "Recall@20": Recall20(yt, yp),
        "ZeroRate": ZeroRate(yp),
        "SPLIT": ("TRAIN" if m <= 23 else ("VAL" if m <= 29 else "TEST"))
    })

xgb_df = pd.DataFrame(rows)

# =========================================================
# 11. FINAL TEST METRICS
# =========================================================
test_df = xgb_df[xgb_df["SPLIT"] == "TEST"]

print("\n===== FINAL XGBOOST METRICS (TEST AVG) =====")
for c in ["MAE", "RMSE", "MAPE", "Accuracy@20", "Recall@20", "ZeroRate"]:
    print(f"{c:12s}: {test_df[c].mean():.6f}")

# =========================================================
# 12. BEST PERFORMING MONTH
# =========================================================
best_row = xgb_df.loc[xgb_df["MAE"].idxmin()]

print("\n===== BEST PERFORMING MONTH (XGBOOST) =====")
for k, v in best_row.items():
    print(f"{k:14s}: {v}")

# =========================================================
# 13. SAVE
# =========================================================
out_path = "/content/drive/MyDrive/Upstream/XGBoost_monthwise_metrics_36months.csv"
xgb_df.to_csv(out_path, index=False)
print("\nSaved:", out_path)

#Hetero-ConvLSTM
# =========================================================
# Hetero-ConvLSTM (NO ROUTE, NO HIGHWAY TYPE)
# GraphConv (neighbors only) + LSTM
# Predict y_{t+1}
# Split: 24 / 6 / 6
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import random

# =========================================================
# 0. SEEDS + DEVICE
# =========================================================
seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# =========================================================
# 1. LOAD DATA
# =========================================================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"], errors="coerce")
df = df.dropna(subset=["YEAR_MONTH"]).copy()
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

months_all = sorted(df["YEAR_MONTH"].unique())
T = len(months_all)
assert T == 36, "Expected 36 months"

# =========================================================
# 2. STATIC SEGMENTS + NEIGHBORS (NO ROUTE TYPE)
# =========================================================
def parse_prefix(seg):
    parts = str(seg).split("_")
    return "_".join(parts[:-2]) if len(parts) >= 3 else str(seg)

def parse_begin(seg):
    try:
        return float(str(seg).split("_")[-2])
    except Exception:
        return np.nan

static_segments = (
    df[["SEGMENT_KEY"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

static_segments["PREFIX"] = static_segments["SEGMENT_KEY"].apply(parse_prefix)
static_segments["BEGIN_MILE"] = static_segments["SEGMENT_KEY"].apply(parse_begin)

segments = static_segments["SEGMENT_KEY"].tolist()
seg2idx = {s: i for i, s in enumerate(segments)}
N = len(segments)
print("Segments:", N)

# Build adjacency (undirected)
neighbors = [[] for _ in range(N)]

for prefix, g in static_segments.groupby("PREFIX"):
    g = g.sort_values("BEGIN_MILE")
    idxs = [seg2idx[s] for s in g["SEGMENT_KEY"].tolist()]
    for i in range(len(idxs) - 1):
        u, v = idxs[i], idxs[i + 1]
        neighbors[u].append(v)
        neighbors[v].append(u)

neighbors = [list(set(n)) for n in neighbors]

# =========================================================
# 3. BUILD X (N,T,F) AND y (N,T)
# =========================================================
numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in ["TOTAL_CRASHES", "YEAR_QUARTER", "YEAR_HALF"]
]

df[numeric_cols] = df[numeric_cols].fillna(0.0)
df["TOTAL_CRASHES"] = df["TOTAL_CRASHES"].fillna(0.0)

F_num = len(numeric_cols)
F_dim = F_num + 1  # + crash history

month2idx = {m: i for i, m in enumerate(months_all)}

X = np.zeros((N, T, F_dim), dtype=np.float32)
y = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = month2idx[r["YEAR_MONTH"]]
    X[i, t, :F_num] = r[numeric_cols].values
    X[i, t, F_num]  = r["TOTAL_CRASHES"]
    y[i, t]         = r["TOTAL_CRASHES"]

X_torch = torch.from_numpy(X).to(device)
y_torch = torch.from_numpy(y).to(device)

# =========================================================
# 4. GRAPH CONV LAYER (MEAN AGGREGATION)
# =========================================================
class GraphConv(nn.Module):
    def __init__(self, in_dim, out_dim, neighbors):
        super().__init__()
        self.neighbors = neighbors
        self.W_self = nn.Linear(in_dim, out_dim)
        self.W_nei  = nn.Linear(in_dim, out_dim)

    def forward(self, h):
        N, d = h.shape
        agg = torch.zeros((N, d), device=h.device)
        for i in range(N):
            if len(self.neighbors[i]) > 0:
                agg[i] = h[self.neighbors[i]].mean(dim=0)
        return F.relu(self.W_self(h) + self.W_nei(agg))

# =========================================================
# 5. HETERO-CONVLSTM MODEL (NO ROUTE)
# =========================================================
class HeteroConvLSTM(nn.Module):
    def __init__(self, Fdim, gnn_dim=64, gnn_layers=2, lstm_dim=64):
        super().__init__()
        self.input_proj = nn.Linear(Fdim, gnn_dim)
        self.gnn = nn.ModuleList([
            GraphConv(gnn_dim, gnn_dim, neighbors)
            for _ in range(gnn_layers)
        ])
        self.lstm = nn.LSTM(gnn_dim, lstm_dim, batch_first=True)
        self.out = nn.Linear(lstm_dim, 1)

    def spatial_encode(self, x_t):
        h = F.relu(self.input_proj(x_t))
        for layer in self.gnn:
            h = layer(h)
        return h

    def forward(self, Xseq):
        # Xseq: (N, Tseq, F)
        H_list = []
        for t in range(Xseq.shape[1]):
            H_list.append(self.spatial_encode(Xseq[:, t, :]).unsqueeze(1))
        H = torch.cat(H_list, dim=1)
        H_lstm, _ = self.lstm(H)
        yhat = self.out(H_lstm[:, :-1, :]).squeeze(-1)
        return F.softplus(yhat)

model = HeteroConvLSTM(F_dim).to(device)

# =========================================================
# 6. TRAIN (24 / 6 / 6)
# =========================================================
train_T, val_T, test_T = 24, 6, 6

opt = torch.optim.Adam(model.parameters(), lr=1e-3)
num_epochs = 12
patience = 4
best_val = float("inf")
best_state = None
bad = 0

for epoch in range(1, num_epochs + 1):
    model.train()
    opt.zero_grad()

    X_train = X_torch[:, :train_T, :]
    pred_train = model(X_train)
    true_train = y_torch[:, 1:train_T]
    loss_train = F.mse_loss(pred_train, true_train)

    loss_train.backward()
    opt.step()

    model.eval()
    with torch.no_grad():
        X_tv = X_torch[:, :train_T + val_T, :]
        pred_tv = model(X_tv)
        val_months = list(range(train_T, train_T + val_T))
        val_idx = [m - 1 for m in val_months]
        pred_val = pred_tv[:, val_idx]
        true_val = y_torch[:, val_months]
        loss_val = F.mse_loss(pred_val, true_val).item()

    print(f"Epoch {epoch:02d} | TrainLoss={loss_train.item():.6f} | ValLoss={loss_val:.6f}")

    if loss_val < best_val - 1e-6:
        best_val = loss_val
        best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        bad = 0
    else:
        bad += 1
        if bad >= patience:
            print("Early stopping")
            break

if best_state is not None:
    model.load_state_dict(best_state)

# =========================================================
# 7. EVALUATION (MONTH-WISE)
# =========================================================
model.eval()
with torch.no_grad():
    pred_all = model(X_torch[:, :T, :]).cpu().numpy()  # (N,35)

def MAE(a,b): return np.mean(np.abs(a-b))
def RMSE(a,b): return np.sqrt(np.mean((a-b)**2))
def MAPE(a,b,eps=1e-6): return np.mean(np.abs((a-b)/np.maximum(a,eps)))
def Acc20(a,b):
    denom = np.sum(a>0)
    if denom == 0: return np.nan
    thr = np.quantile(b,0.8)
    return np.sum((a>0)&(b>=thr))/denom
def Recall20(a,b):
    K = max(1,int(0.2*len(a)))
    return len(set(np.argsort(-a)[:K]) & set(np.argsort(-b)[:K]))/K
def ZeroRate(b): return np.mean(b<1e-6)

rows = []
for m in range(1, T):
    yt = y[:, m]
    yp = pred_all[:, m-1]
    rows.append({
        "YEAR_MONTH": months_all[m],
        "MONTH_INDEX": m,
        "MAE": MAE(yt, yp),
        "RMSE": RMSE(yt, yp),
        "MAPE": MAPE(yt, yp),
        "Accuracy@20": Acc20(yt, yp),
        "Recall@20": Recall20(yt, yp),
        "ZeroRate": ZeroRate(yp),
        "SPLIT": ("TRAIN" if m<=23 else ("VAL" if m<=29 else "TEST"))
    })

hetero_df = pd.DataFrame(rows)
print(hetero_df.head())

out_path = "/content/drive/MyDrive/Upstream/HeteroConvLSTM_monthwise_metrics_36months.csv"
hetero_df.to_csv(out_path, index=False)
print("Saved:", out_path)

# DFTAR
# =========================================================
# DF-TAR (Deep Forecasting – Temporal AutoRegression)
# - GRU over lagged crash history + numeric features
# - NO spatial graph
# - Epochs = 10 (as requested)
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
import random

# =========================================================
# 0. SEEDS + DEVICE
# =========================================================
seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# =========================================================
# 1. LOAD DATA
# =========================================================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"])
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

segments = sorted(df["SEGMENT_KEY"].unique())
months   = sorted(df["YEAR_MONTH"].unique())
N = len(segments)
T = len(months)
assert T == 36

seg2idx = {s:i for i,s in enumerate(segments)}
mon2idx = {m:i for i,m in enumerate(months)}

# =========================================================
# 2. NUMERIC FEATURES
# =========================================================
numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in ["TOTAL_CRASHES", "YEAR_QUARTER", "YEAR_HALF"]
]

df[numeric_cols] = df[numeric_cols].fillna(0.0)
df["TOTAL_CRASHES"] = df["TOTAL_CRASHES"].fillna(0.0)

F_num = len(numeric_cols)

# =========================================================
# 3. BUILD MATRICES
# =========================================================
X_full = np.zeros((N, T, F_num), dtype=np.float32)
y_full = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = mon2idx[r["YEAR_MONTH"]]
    X_full[i, t, :] = r[numeric_cols].values
    y_full[i, t]    = r["TOTAL_CRASHES"]

# =========================================================
# 4. BUILD DF-TAR SUPERVISED SEQUENCES
# Sequence length = 4
# [X_{t-3}, X_{t-2}, X_{t-1}, X_t] -> y_{t+1}
# =========================================================
SEQ_LEN = 4

Xs, ys, ms = [], [], []

for i in range(N):
    for m in range(SEQ_LEN, T-1):   # predict m+1
        seq_feats = []
        for k in range(m-SEQ_LEN, m):
            seq_feats.append(
                np.hstack([X_full[i, k, :], y_full[i, k]])
            )
        Xs.append(seq_feats)
        ys.append(y_full[i, m])
        ms.append(m)

Xs = np.asarray(Xs, dtype=np.float32)   # (samples, seq, features)
ys = np.asarray(ys, dtype=np.float32)
ms = np.asarray(ms, dtype=np.int32)

F_in = Xs.shape[2]

# =========================================================
# 5. SPLIT (NO FUTURE PEEK)
# =========================================================
train_mask = (ms <= 23)
val_mask   = (ms >= 24) & (ms <= 29)
test_mask  = (ms >= 30)

X_train, y_train = Xs[train_mask], ys[train_mask]
X_val,   y_val   = Xs[val_mask],   ys[val_mask]
X_test,  y_test  = Xs[test_mask],  ys[test_mask]

m_train = ms[train_mask]
m_val   = ms[val_mask]
m_test  = ms[test_mask]

# =========================================================
# 6. DATASET
# =========================================================
class SeqDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X)
        self.y = torch.from_numpy(y).view(-1, 1)
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_loader = DataLoader(SeqDataset(X_train, y_train), batch_size=4096, shuffle=True)
val_loader   = DataLoader(SeqDataset(X_val, y_val), batch_size=4096, shuffle=False)

# =========================================================
# 7. DF-TAR MODEL
# =========================================================
class DFTAR(nn.Module):
    def __init__(self, in_dim, hidden_dim=64):
        super().__init__()
        self.gru = nn.GRU(in_dim, hidden_dim, batch_first=True)
        self.fc  = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        h, _ = self.gru(x)
        out = self.fc(h[:, -1, :])
        return F.softplus(out)

model = DFTAR(F_in).to(device)
opt = torch.optim.Adam(model.parameters(), lr=1e-3)

# =========================================================
# 8. TRAIN (EXACTLY 10 EPOCHS)
# =========================================================
for epoch in range(1, 11):
    model.train()
    losses = []

    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)
        pred = model(xb)
        loss = F.mse_loss(pred, yb)

        opt.zero_grad()
        loss.backward()
        opt.step()
        losses.append(loss.item())

    model.eval()
    with torch.no_grad():
        vloss = []
        for xb, yb in val_loader:
            xb, yb = xb.to(device), yb.to(device)
            vloss.append(F.mse_loss(model(xb), yb).item())

    print(f"Epoch {epoch:02d} | TrainMSE={np.mean(losses):.6f} | ValMSE={np.mean(vloss):.6f}")

# =========================================================
# 9. PREDICT ALL MONTHS
# =========================================================
model.eval()
with torch.no_grad():
    preds = model(torch.from_numpy(Xs).to(device)).cpu().numpy().flatten()

y_pred = np.zeros((N, T-1), dtype=np.float32)
idx = 0
for i in range(N):
    for m in range(SEQ_LEN, T-1):
        y_pred[i, m] = preds[idx]
        idx += 1

# =========================================================
# 10. METRICS
# =========================================================
def MAE(a,b): return np.mean(np.abs(a-b))
def RMSE(a,b): return np.sqrt(np.mean((a-b)**2))
def MAPE(a,b,eps=1e-6): return np.mean(np.abs((a-b)/np.maximum(a,eps)))
def AccHR20(a,b):
    denom = np.sum(a>0)
    if denom == 0: return np.nan
    thr = np.quantile(b,0.8)
    return np.sum((a>0)&(b>=thr))/denom
def Recall20(a,b):
    K = max(1,int(0.2*len(a)))
    return len(set(np.argsort(-a)[:K]) & set(np.argsort(-b)[:K]))/K
def ZeroRate(b): return np.mean(b<1e-6)

rows = []
for m in range(1, T):   # months 1..35
    yt = y_full[:, m]          # actual crashes at month m
    yp = y_pred[:, m-1]        # prediction aligned to month m

    rows.append({
        "YEAR_MONTH": months[m],
        "MONTH_INDEX": m,
        "MAE": MAE(yt, yp),
        "RMSE": RMSE(yt, yp),
        "MAPE": MAPE(yt, yp),
        "Accuracy@20": AccHR20(yt, yp),
        "Recall@20": Recall20(yt, yp),
        "ZeroRate": ZeroRate(yp),
        "SPLIT": ("TRAIN" if m <= 23 else ("VAL" if m <= 29 else "TEST"))
    })

df_tar = pd.DataFrame(rows)


# =========================================================
# 11. FINAL RESULTS
# =========================================================
test_df = df_tar[df_tar["SPLIT"]=="TEST"]

print("\n===== FINAL DF-TAR METRICS (TEST AVG) =====")
for c in ["MAE","RMSE","MAPE","Accuracy@20","Recall@20","ZeroRate"]:
    print(f"{c:12s}: {test_df[c].mean():.6f}")

best_row = df_tar.loc[df_tar["MAE"].idxmin()]
print("\n===== BEST PERFORMING MONTH (DF-TAR) =====")
for k,v in best_row.items():
    print(f"{k:14s}: {v}")

# =========================================================
# 12. SAVE
# =========================================================
out_path = "/content/drive/MyDrive/Upstream/DF_TAR_monthwise_metrics_36months.csv"
df_tar.to_csv(out_path, index=False)
print("\nSaved:", out_path)

#STNB-GNN
# =========================================================
# STNB-GNN (Spatio-Temporal Negative Binomial GNN)
# - GraphSAGE-style spatial aggregation (NO upstream)
# - GRU temporal modeling
# - Negative Binomial likelihood
# - Epochs = 10
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import random

# =========================================================
# 0. SEEDS + DEVICE
# =========================================================
seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# =========================================================
# 1. LOAD DATA
# =========================================================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"])
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

segments = sorted(df["SEGMENT_KEY"].unique())
months   = sorted(df["YEAR_MONTH"].unique())
N = len(segments)
T = len(months)
assert T == 36

seg2idx = {s:i for i,s in enumerate(segments)}
mon2idx = {m:i for i,m in enumerate(months)}

# =========================================================
# 2. BUILD NEIGHBORS (ROUTE-WISE, NO UPSTREAM)
# =========================================================
def parse_prefix(seg):
    parts = str(seg).split("_")
    return "_".join(parts[:-2]) if len(parts) >= 3 else str(seg)

def parse_begin(seg):
    try:
        return float(str(seg).split("_")[-2])
    except:
        return np.nan

static = (
    df[["SEGMENT_KEY"]]
    .drop_duplicates()
    .assign(PREFIX=lambda x: x["SEGMENT_KEY"].apply(parse_prefix),
            BEGIN=lambda x: x["SEGMENT_KEY"].apply(parse_begin))
)

neighbors = [[] for _ in range(N)]
for _, g in static.groupby("PREFIX"):
    g = g.sort_values("BEGIN")
    idxs = [seg2idx[s] for s in g["SEGMENT_KEY"]]
    for i in range(len(idxs)-1):
        u, v = idxs[i], idxs[i+1]
        neighbors[u].append(v)
        neighbors[v].append(u)

neighbors = [sorted(set(n)) for n in neighbors]

# =========================================================
# 3. FEATURES
# =========================================================
numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in ["TOTAL_CRASHES", "YEAR_QUARTER", "YEAR_HALF"]
]

df[numeric_cols] = df[numeric_cols].fillna(0.0)
df["TOTAL_CRASHES"] = df["TOTAL_CRASHES"].fillna(0.0)

F_num = len(numeric_cols)
F_dim = F_num + 1  # + crash history

X = np.zeros((N, T, F_dim), dtype=np.float32)
y = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = mon2idx[r["YEAR_MONTH"]]
    X[i, t, :F_num] = r[numeric_cols].values
    X[i, t, F_num]  = r["TOTAL_CRASHES"]
    y[i, t]         = r["TOTAL_CRASHES"]

X_t = torch.from_numpy(X).to(device)
y_t = torch.from_numpy(y).to(device)

# =========================================================
# 4. STNB-GNN MODEL
# =========================================================
class SpatialMean(nn.Module):
    def __init__(self, dim, neighbors):
        super().__init__()
        self.neighbors = neighbors
        self.lin = nn.Linear(dim*2, dim)

    def forward(self, h):
        N, d = h.shape
        agg = torch.zeros_like(h)
        for i in range(N):
            if len(self.neighbors[i]) > 0:
                agg[i] = h[self.neighbors[i]].mean(dim=0)
        return F.relu(self.lin(torch.cat([h, agg], dim=1)))

class STNB_GNN(nn.Module):
    def __init__(self, Fdim, gnn_dim=64, gru_dim=64, gnn_layers=2):
        super().__init__()
        self.in_proj = nn.Linear(Fdim, gnn_dim)
        self.gnn = nn.ModuleList([SpatialMean(gnn_dim, neighbors) for _ in range(gnn_layers)])
        self.gru = nn.GRU(gnn_dim, gru_dim, batch_first=True)
        self.mu_head = nn.Linear(gru_dim, 1)
        self.log_theta = nn.Parameter(torch.tensor(0.0))  # dispersion

    def forward(self, Xseq):
        Nn, Tseq, _ = Xseq.shape
        Hs = []
        for t in range(Tseq):
            h = F.relu(self.in_proj(Xseq[:, t, :]))
            for layer in self.gnn:
                h = layer(h)
            Hs.append(h.unsqueeze(1))
        Hs = torch.cat(Hs, dim=1)
        H, _ = self.gru(Hs)
        mu = F.softplus(self.mu_head(H[:, :-1, :])).squeeze(-1)
        theta = torch.exp(self.log_theta)
        return mu, theta

def nb_nll(y, mu, theta):
    return torch.mean(
        torch.lgamma(y + theta) - torch.lgamma(theta) - torch.lgamma(y + 1)
        + theta * torch.log(theta / (theta + mu))
        + y * torch.log(mu / (theta + mu))
    ) * -1

# =========================================================
# 5. TRAIN (10 EPOCHS)
# =========================================================
train_T, val_T = 24, 6
model = STNB_GNN(F_dim).to(device)
opt = torch.optim.Adam(model.parameters(), lr=1e-3)

for epoch in range(1, 11):
    model.train()
    mu, theta = model(X_t[:, :train_T, :])
    loss = nb_nll(y_t[:, 1:train_T], mu, theta)

    opt.zero_grad()
    loss.backward()
    opt.step()

    print(f"Epoch {epoch:02d} | NLL={loss.item():.6f}")

# =========================================================
# 6. PREDICT ALL MONTHS
# =========================================================
model.eval()
with torch.no_grad():
    mu_all, _ = model(X_t[:, :T, :])
    y_pred = mu_all.cpu().numpy()   # (N, 35)

# =========================================================
# 7. METRICS
# =========================================================
def MAE(a,b): return np.mean(np.abs(a-b))
def RMSE(a,b): return np.sqrt(np.mean((a-b)**2))
def MAPE(a,b,eps=1e-6): return np.mean(np.abs((a-b)/np.maximum(a,eps)))
def AccHR20(a,b):
    denom = np.sum(a>0)
    if denom==0: return np.nan
    thr = np.quantile(b,0.8)
    return np.sum((a>0)&(b>=thr))/denom
def Recall20(a,b):
    K=max(1,int(0.2*len(a)))
    return len(set(np.argsort(-a)[:K]) & set(np.argsort(-b)[:K]))/K
def ZeroRate(b): return np.mean(b<1e-6)

rows=[]
for m in range(1,T):
    rows.append({
        "YEAR_MONTH": months[m],
        "MONTH_INDEX": m,
        "MAE": MAE(y[:,m], y_pred[:,m-1]),
        "RMSE": RMSE(y[:,m], y_pred[:,m-1]),
        "MAPE": MAPE(y[:,m], y_pred[:,m-1]),
        "Accuracy@20": AccHR20(y[:,m], y_pred[:,m-1]),
        "Recall@20": Recall20(y[:,m], y_pred[:,m-1]),
        "ZeroRate": ZeroRate(y_pred[:,m-1]),
        "SPLIT": ("TRAIN" if m<=23 else ("VAL" if m<=29 else "TEST"))
    })

stnb_df = pd.DataFrame(rows)

# =========================================================
# 8. FINAL RESULTS
# =========================================================
test_df = stnb_df[stnb_df["SPLIT"]=="TEST"]
print("\n===== FINAL STNB-GNN METRICS (TEST AVG) =====")
for c in ["MAE","RMSE","MAPE","Accuracy@20","Recall@20","ZeroRate"]:
    print(f"{c:12s}: {test_df[c].mean():.6f}")

best = stnb_df.loc[stnb_df["MAE"].idxmin()]
print("\n===== BEST PERFORMING MONTH (STNB-GNN) =====")
print(best)

# =========================================================
# 9. SAVE
# =========================================================
out_path = "/content/drive/MyDrive/Upstream/STNB_GNN_monthwise_metrics_36months.csv"
stnb_df.to_csv(out_path, index=False)
print("\nSaved:", out_path)

#STG-GNN
# =========================================================
# STG-GNN BASELINE (10 epochs)
# - Spatial: GraphSAGE-style mean aggregation (NO upstream, NO attention)
# - Temporal: GRU
# - Output: non-negative crash intensity via Softplus (Poisson-mean style)
# - Predict next month y_{t+1}
# - Split: 24/6/6 (same as your pipeline)
# - Save: month-wise metrics CSV (months 1..35)
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import random

# =========================================================
# 0) SEEDS + DEVICE
# =========================================================
seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# =========================================================
# 1) LOAD DATA
# =========================================================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"], errors="coerce")
df = df.dropna(subset=["YEAR_MONTH"]).copy()
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

segments = sorted(df["SEGMENT_KEY"].unique())
months_all = sorted(df["YEAR_MONTH"].unique())
N = len(segments)
T = len(months_all)
print("Segments:", N, "| Months:", T, "|", months_all[0], "->", months_all[-1])
assert T == 36, "Expected 36 months."

seg2idx = {s:i for i,s in enumerate(segments)}
mon2idx = {m:i for i,m in enumerate(months_all)}

# =========================================================
# 2) BUILD NEIGHBORS (ROUTE-WISE using SEGMENT_KEY prefix + begin mile)
# =========================================================
def parse_prefix(seg):
    parts = str(seg).split("_")
    return "_".join(parts[:-2]) if len(parts) >= 3 else str(seg)

def parse_begin(seg):
    try:
        return float(str(seg).split("_")[-2])
    except Exception:
        return np.nan

static = (
    df[["SEGMENT_KEY"]]
    .drop_duplicates()
    .assign(PREFIX=lambda x: x["SEGMENT_KEY"].apply(parse_prefix),
            BEGIN_MILE=lambda x: x["SEGMENT_KEY"].apply(parse_begin))
)

neighbors = [[] for _ in range(N)]
for prefix, g in static.groupby("PREFIX"):
    g = g.sort_values("BEGIN_MILE")
    idxs = [seg2idx[s] for s in g["SEGMENT_KEY"].tolist()]
    for i in range(len(idxs) - 1):
        u, v = idxs[i], idxs[i + 1]
        neighbors[u].append(v)
        neighbors[v].append(u)

neighbors = [sorted(set(n)) for n in neighbors]

# =========================================================
# 3) BUILD X (N,T,F) AND y (N,T)
# =========================================================
numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in ["TOTAL_CRASHES", "YEAR_QUARTER", "YEAR_HALF"]
]

df[numeric_cols] = df[numeric_cols].fillna(0.0)
df["TOTAL_CRASHES"] = df["TOTAL_CRASHES"].fillna(0.0)

F_num = len(numeric_cols)
F_dim = F_num + 1  # + crash history

X = np.zeros((N, T, F_dim), dtype=np.float32)
y = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = mon2idx[r["YEAR_MONTH"]]
    X[i, t, :F_num] = r[numeric_cols].values.astype(np.float32)
    X[i, t, F_num]  = float(r["TOTAL_CRASHES"])  # crash history channel
    y[i, t]         = float(r["TOTAL_CRASHES"])

X_t = torch.from_numpy(X).to(device)
y_t = torch.from_numpy(y).to(device)

# =========================================================
# 4) MODEL: STG-GNN (GraphSAGE mean + GRU)
# =========================================================
class GraphSAGELayer(nn.Module):
    def __init__(self, dim, neighbors, dropout=0.0):
        super().__init__()
        self.neighbors = neighbors
        self.lin = nn.Linear(dim * 2, dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, h):
        Nn, d = h.shape
        agg = torch.zeros((Nn, d), device=h.device)

        for i in range(Nn):
            nei = self.neighbors[i]
            if len(nei) > 0:
                agg[i] = h[nei].mean(dim=0)

        out = self.lin(torch.cat([h, agg], dim=1))
        out = F.relu(out)
        return self.dropout(out)

class STGGNN(nn.Module):
    def __init__(self, Fdim, gnn_dim=64, gnn_layers=2, gru_dim=64, dropout=0.1):
        super().__init__()
        self.in_proj = nn.Linear(Fdim, gnn_dim)
        self.sage = nn.ModuleList([
            GraphSAGELayer(gnn_dim, neighbors, dropout=dropout)
            for _ in range(gnn_layers)
        ])
        self.gru = nn.GRU(gnn_dim, gru_dim, batch_first=True)
        self.out = nn.Linear(gru_dim, 1)

    def spatial_encode(self, x_t):
        h = F.relu(self.in_proj(x_t))
        for layer in self.sage:
            h = layer(h)
        return h

    def forward(self, Xseq):
        # Xseq: (N, Tseq, F)
        Nn, Tseq, _ = Xseq.shape
        H_list = []
        for t in range(Tseq):
            H_list.append(self.spatial_encode(Xseq[:, t, :]).unsqueeze(1))
        Hs = torch.cat(H_list, dim=1)            # (N, Tseq, gnn_dim)
        H, _ = self.gru(Hs)                      # (N, Tseq, gru_dim)
        yhat = self.out(H[:, :-1, :]).squeeze(-1)  # (N, Tseq-1)
        return F.softplus(yhat)                  # non-negative

model = STGGNN(F_dim, gnn_dim=64, gnn_layers=2, gru_dim=64, dropout=0.1).to(device)
opt = torch.optim.Adam(model.parameters(), lr=1e-3)

# =========================================================
# 5) SPLIT (24/6/6) + TRAIN (10 epochs)
# =========================================================
train_T, val_T, test_T = 24, 6, 6
assert train_T + val_T + test_T == T

for epoch in range(1, 11):  # EXACTLY 10 epochs
    model.train()
    opt.zero_grad()

    # Train: feed 0..23 -> predict 1..23
    X_train = X_t[:, :train_T, :]
    pred_train = model(X_train)               # (N, 23)
    true_train = y_t[:, 1:train_T]            # (N, 23)
    loss = F.mse_loss(pred_train, true_train)

    loss.backward()
    opt.step()

    # Val: feed 0..29 -> pick preds for months 24..29
    model.eval()
    with torch.no_grad():
        X_tv = X_t[:, :train_T + val_T, :]
        pred_tv = model(X_tv)                 # predicts months 1..29
        val_months = list(range(train_T, train_T + val_T))  # 24..29
        val_idx = [m - 1 for m in val_months]               # 23..28
        pred_val = pred_tv[:, val_idx]
        true_val = y_t[:, val_months]
        val_loss = F.mse_loss(pred_val, true_val).item()

    print(f"Epoch {epoch:02d} | TrainMSE={loss.item():.6f} | ValMSE={val_loss:.6f}")

# =========================================================
# 6) PREDICT ALL MONTHS (1..35)
# =========================================================
model.eval()
with torch.no_grad():
    pred_all = model(X_t[:, :T, :]).detach().cpu().numpy()  # (N, 35)

# =========================================================
# 7) METRICS (month-wise)
# =========================================================
def MAE(a,b): return float(np.mean(np.abs(a-b)))
def RMSE(a,b): return float(np.sqrt(np.mean((a-b)**2)))
def MAPE(a,b,eps=1e-6): return float(np.mean(np.abs((a-b)/np.maximum(a,eps))))
def AccHR20(a,b):
    denom = np.sum(a > 0)
    if denom == 0: return np.nan
    thr = np.quantile(b, 0.8)
    return float(np.sum((a > 0) & (b >= thr)) / denom)
def Recall20(a,b):
    K = max(1, int(0.2 * len(a)))
    return float(len(set(np.argsort(-a)[:K]) & set(np.argsort(-b)[:K])) / K)
def ZeroRate(b): return float(np.mean(b < 1e-6))

rows = []
for m in range(1, T):  # months 1..35
    yt = y[:, m]
    yp = pred_all[:, m-1]
    rows.append({
        "YEAR_MONTH": months_all[m],
        "MONTH_INDEX": m,
        "MAE": MAE(yt, yp),
        "RMSE": RMSE(yt, yp),
        "MAPE": MAPE(yt, yp),
        "Accuracy@20": AccHR20(yt, yp),
        "Recall@20": Recall20(yt, yp),
        "ZeroRate": ZeroRate(yp),
        "SPLIT": ("TRAIN" if m <= 23 else ("VAL" if m <= 29 else "TEST"))
    })

stg_df = pd.DataFrame(rows)

# =========================================================
# 8) FINAL TEST METRICS + BEST MONTH
# =========================================================
test_df = stg_df[stg_df["SPLIT"] == "TEST"]
print("\n===== FINAL STG-GNN METRICS (TEST AVG) =====")
for c in ["MAE","RMSE","MAPE","Accuracy@20","Recall@20","ZeroRate"]:
    print(f"{c:12s}: {test_df[c].mean():.6f}")

best_row = stg_df.loc[stg_df["MAE"].idxmin()]
print("\n===== BEST PERFORMING MONTH (STG-GNN) =====")
for k, v in best_row.items():
    print(f"{k:14s}: {v}")

# =========================================================
# 9) SAVE
# =========================================================
out_path = "/content/drive/MyDrive/Upstream/STG_GNN_monthwise_metrics_36months.csv"
stg_df.to_csv(out_path, index=False)
print("\nSaved:", out_path)

# optional: save model
model_path = "/content/drive/MyDrive/Upstream/STG_GNN_houston_10epochs.pth"
torch.save(model.state_dict(), model_path)
print("Saved model:", model_path)

#STGAT
# =========================================================
# STGAT BASELINE (10 epochs)
# - Spatial: GAT-style neighbor attention (NO upstream)
# - Temporal: GRU
# - Output: non-negative crash intensity via Softplus
# - Predict next month y_{t+1}
# - Split: 24/6/6 (same as your pipeline)
# - Save: month-wise metrics CSV (months 1..35)
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import random

# =========================================================
# 0) SEEDS + DEVICE
# =========================================================
seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# =========================================================
# 1) LOAD DATA
# =========================================================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"], errors="coerce")
df = df.dropna(subset=["YEAR_MONTH"]).copy()
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

segments = sorted(df["SEGMENT_KEY"].unique())
months_all = sorted(df["YEAR_MONTH"].unique())
N = len(segments)
T = len(months_all)
print("Segments:", N, "| Months:", T, "|", months_all[0], "->", months_all[-1])
assert T == 36, "Expected 36 months."

seg2idx = {s:i for i,s in enumerate(segments)}
mon2idx = {m:i for i,m in enumerate(months_all)}

# =========================================================
# 2) BUILD NEIGHBORS (ROUTE-WISE using SEGMENT_KEY prefix + begin mile)
# =========================================================
def parse_prefix(seg):
    parts = str(seg).split("_")
    return "_".join(parts[:-2]) if len(parts) >= 3 else str(seg)

def parse_begin(seg):
    try:
        return float(str(seg).split("_")[-2])
    except Exception:
        return np.nan

static = (
    df[["SEGMENT_KEY"]]
    .drop_duplicates()
    .assign(PREFIX=lambda x: x["SEGMENT_KEY"].apply(parse_prefix),
            BEGIN_MILE=lambda x: x["SEGMENT_KEY"].apply(parse_begin))
)

neighbors = [[] for _ in range(N)]
for prefix, g in static.groupby("PREFIX"):
    g = g.sort_values("BEGIN_MILE")
    idxs = [seg2idx[s] for s in g["SEGMENT_KEY"].tolist()]
    for i in range(len(idxs) - 1):
        u, v = idxs[i], idxs[i + 1]
        neighbors[u].append(v)
        neighbors[v].append(u)

neighbors = [sorted(set(n)) for n in neighbors]

# =========================================================
# 3) BUILD X (N,T,F) AND y (N,T)
# =========================================================
numeric_cols = [
    c for c in df.select_dtypes(include=[np.number]).columns
    if c not in ["TOTAL_CRASHES", "YEAR_QUARTER", "YEAR_HALF"]
]

df[numeric_cols] = df[numeric_cols].fillna(0.0)
df["TOTAL_CRASHES"] = df["TOTAL_CRASHES"].fillna(0.0)

F_num = len(numeric_cols)
F_dim = F_num + 1  # + crash history

X = np.zeros((N, T, F_dim), dtype=np.float32)
y = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = mon2idx[r["YEAR_MONTH"]]
    X[i, t, :F_num] = r[numeric_cols].values.astype(np.float32)
    X[i, t, F_num]  = float(r["TOTAL_CRASHES"])  # crash history channel
    y[i, t]         = float(r["TOTAL_CRASHES"])

X_t = torch.from_numpy(X).to(device)
y_t = torch.from_numpy(y).to(device)

# =========================================================
# 4) MODEL: STGAT (GAT neighbor attention + GRU)
# =========================================================
class GATLayer(nn.Module):
    """
    Single-head GAT over neighbor lists (no upstream).
    out_i = ReLU( W h_i + sum_j alpha_ij W h_j )
    alpha_ij = softmax_j( LeakyReLU( a^T [W h_i || W h_j] ) )
    """
    def __init__(self, dim, neighbors):
        super().__init__()
        self.neighbors = neighbors
        self.W = nn.Linear(dim, dim, bias=False)
        self.a = nn.Linear(2 * dim, 1, bias=False)
        self.leaky = nn.LeakyReLU(0.2)

    def forward(self, h):
        Nn, d = h.shape
        Wh = self.W(h)  # (N,d)
        out = torch.zeros((Nn, d), device=h.device)

        for i in range(Nn):
            nei = self.neighbors[i]
            if len(nei) == 0:
                out[i] = Wh[i]
                continue

            Wh_i = Wh[i].unsqueeze(0).expand(len(nei), -1)   # (k,d)
            Wh_j = Wh[nei]                                   # (k,d)

            e = self.leaky(self.a(torch.cat([Wh_i, Wh_j], dim=1))).view(-1)  # (k,)
            alpha = torch.softmax(e, dim=0)                                  # (k,)

            out[i] = Wh[i] + torch.sum(alpha[:, None] * Wh_j, dim=0)

        return F.relu(out)

class STGAT(nn.Module):
    def __init__(self, Fdim, gat_dim=64, gat_layers=2, gru_dim=64, dropout=0.1):
        super().__init__()
        self.in_proj = nn.Linear(Fdim, gat_dim)
        self.gat = nn.ModuleList([GATLayer(gat_dim, neighbors) for _ in range(gat_layers)])
        self.dropout = nn.Dropout(dropout)
        self.gru = nn.GRU(gat_dim, gru_dim, batch_first=True)
        self.out = nn.Linear(gru_dim, 1)

    def spatial_encode(self, x_t):
        h = F.relu(self.in_proj(x_t))
        for layer in self.gat:
            h = layer(h)
            h = self.dropout(h)
        return h

    def forward(self, Xseq):
        # Xseq: (N, Tseq, F)
        Nn, Tseq, _ = Xseq.shape
        H_list = []
        for t in range(Tseq):
            H_list.append(self.spatial_encode(Xseq[:, t, :]).unsqueeze(1))
        Hs = torch.cat(H_list, dim=1)             # (N,Tseq,gat_dim)
        H, _ = self.gru(Hs)                       # (N,Tseq,gru_dim)
        yhat = self.out(H[:, :-1, :]).squeeze(-1) # (N,Tseq-1)
        return F.softplus(yhat)

model = STGAT(F_dim, gat_dim=64, gat_layers=2, gru_dim=64, dropout=0.1).to(device)
opt = torch.optim.Adam(model.parameters(), lr=1e-3)

# =========================================================
# 5) TRAIN (24/6/6) - EXACTLY 10 epochs
# =========================================================
train_T, val_T, test_T = 24, 6, 6
assert train_T + val_T + test_T == T

for epoch in range(1, 11):
    model.train()
    opt.zero_grad()

    # Train: feed 0..23 -> predict 1..23
    X_train = X_t[:, :train_T, :]
    pred_train = model(X_train)               # (N, 23)
    true_train = y_t[:, 1:train_T]            # (N, 23)
    loss = F.mse_loss(pred_train, true_train)

    loss.backward()
    opt.step()

    # Val: feed 0..29 -> evaluate preds for 24..29
    model.eval()
    with torch.no_grad():
        X_tv = X_t[:, :train_T + val_T, :]
        pred_tv = model(X_tv)                 # predicts months 1..29
        val_months = list(range(train_T, train_T + val_T))  # 24..29
        val_idx = [m - 1 for m in val_months]               # 23..28
        pred_val = pred_tv[:, val_idx]
        true_val = y_t[:, val_months]
        val_loss = F.mse_loss(pred_val, true_val).item()

    print(f"Epoch {epoch:02d} | TrainMSE={loss.item():.6f} | ValMSE={val_loss:.6f}")

# =========================================================
# 6) PREDICT ALL MONTHS (1..35)
# =========================================================
model.eval()
with torch.no_grad():
    pred_all = model(X_t[:, :T, :]).detach().cpu().numpy()  # (N,35)

# =========================================================
# 7) METRICS (month-wise)
# =========================================================
def MAE(a,b): return float(np.mean(np.abs(a-b)))
def RMSE(a,b): return float(np.sqrt(np.mean((a-b)**2)))
def MAPE(a,b,eps=1e-6): return float(np.mean(np.abs((a-b)/np.maximum(a,eps))))
def AccHR20(a,b):
    denom = np.sum(a > 0)
    if denom == 0: return np.nan
    thr = np.quantile(b, 0.8)
    return float(np.sum((a > 0) & (b >= thr)) / denom)
def Recall20(a,b):
    K = max(1, int(0.2 * len(a)))
    return float(len(set(np.argsort(-a)[:K]) & set(np.argsort(-b)[:K])) / K)
def ZeroRate(b): return float(np.mean(b < 1e-6))

rows = []
for m in range(1, T):  # months 1..35
    yt = y[:, m]
    yp = pred_all[:, m-1]
    rows.append({
        "YEAR_MONTH": months_all[m],
        "MONTH_INDEX": m,
        "MAE": MAE(yt, yp),
        "RMSE": RMSE(yt, yp),
        "MAPE": MAPE(yt, yp),
        "Accuracy@20": AccHR20(yt, yp),
        "Recall@20": Recall20(yt, yp),
        "ZeroRate": ZeroRate(yp),
        "SPLIT": ("TRAIN" if m <= 23 else ("VAL" if m <= 29 else "TEST"))
    })

stgat_df = pd.DataFrame(rows)

# =========================================================
# 8) FINAL TEST METRICS + BEST MONTH
# =========================================================
test_df = stgat_df[stgat_df["SPLIT"] == "TEST"]
print("\n===== FINAL STGAT METRICS (TEST AVG) =====")
for c in ["MAE","RMSE","MAPE","Accuracy@20","Recall@20","ZeroRate"]:
    print(f"{c:12s}: {test_df[c].mean():.6f}")

best_row = stgat_df.loc[stgat_df["MAE"].idxmin()]
print("\n===== BEST PERFORMING MONTH (STGAT) =====")
for k, v in best_row.items():
    print(f"{k:14s}: {v}")

# =========================================================
# 9) SAVE
# =========================================================
out_path = "/content/drive/MyDrive/Upstream/STGAT_monthwise_metrics_36months.csv"
stgat_df.to_csv(out_path, index=False)
print("\nSaved:", out_path)

# optional: save model
model_path = "/content/drive/MyDrive/Upstream/STGAT_houston_10epochs.pth"
torch.save(model.state_dict(), model_path)
print("Saved model:", model_path)

# =========================================================
# SIMPLE ARIMA BASELINE (AR(1))
# - Rolling one-step-ahead prediction
# - Per segment
# - Month-wise MAE / RMSE / etc.
# - Output CSV identical to STGAT format
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tools.sm_exceptions import ConvergenceWarning
import warnings

warnings.filterwarnings("ignore", category=ConvergenceWarning)
warnings.filterwarnings("ignore", category=UserWarning)

# =========================================================
# 1) LOAD DATA
# =========================================================
csv_path = "/content/drive/MyDrive/Upstream/final_houston_36month_panel_UPDATED.csv"
df = pd.read_csv(csv_path)

df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")
df["YEAR_MONTH"] = pd.to_datetime(df["YEAR_MONTH"], errors="coerce")
df = df.dropna(subset=["YEAR_MONTH"]).copy()
df = df.sort_values(["SEGMENT_KEY", "YEAR_MONTH"])

segments = sorted(df["SEGMENT_KEY"].unique())
months_all = sorted(df["YEAR_MONTH"].unique())

N = len(segments)
T = len(months_all)

print("Segments:", N)
print("Months:", T)
assert T == 36, "Expected exactly 36 months"

seg2idx = {s: i for i, s in enumerate(segments)}
mon2idx = {m: i for i, m in enumerate(months_all)}

# =========================================================
# 2) BUILD y MATRIX (N, 36)
# =========================================================
y = np.zeros((N, T), dtype=np.float32)

for _, r in df.iterrows():
    i = seg2idx[r["SEGMENT_KEY"]]
    t = mon2idx[r["YEAR_MONTH"]]
    y[i, t] = float(r["TOTAL_CRASHES"])

# =========================================================
# 3) ROLLING ARIMA (AR(1)) PER SEGMENT
# =========================================================
def rolling_arima(y_seg, min_hist=3):
    """
    Rolling one-step-ahead ARIMA(1,0,0)
    Returns predictions for months 1..35
    """
    preds = np.full(T-1, np.nan)

    for m in range(1, T):
        hist = y_seg[:m]

        # fallback: too short or constant
        if m < min_hist or np.allclose(hist, hist[0]):
            preds[m-1] = hist.mean()
            continue

        try:
            model = ARIMA(hist, order=(1,0,0), trend="c")
            res = model.fit()
            preds[m-1] = res.forecast(1)[0]
        except:
            preds[m-1] = hist.mean()

    return np.clip(preds, 0, None)

# =========================================================
# 4) PREDICT ALL SEGMENTS
# =========================================================
arima_pred = np.zeros((N, T-1), dtype=np.float32)

for i in range(N):
    arima_pred[i] = rolling_arima(y[i])

print("ARIMA prediction shape:", arima_pred.shape)  # (N, 35)

# =========================================================
# 5) METRIC FUNCTIONS (IDENTICAL TO STGAT)
# =========================================================
def MAE(a,b): return float(np.mean(np.abs(a-b)))
def RMSE(a,b): return float(np.sqrt(np.mean((a-b)**2)))
def MAPE(a,b,eps=1e-6): return float(np.mean(np.abs((a-b)/np.maximum(a,eps))))

def AccHR20(a,b):
    denom = np.sum(a > 0)
    if denom == 0:
        return np.nan
    thr = np.quantile(b, 0.8)
    return float(np.sum((a > 0) & (b >= thr)) / denom)

def Recall20(a,b):
    K = max(1, int(0.2 * len(a)))
    return float(len(set(np.argsort(-a)[:K]) & set(np.argsort(-b)[:K])) / K)

def ZeroRate(b):
    return float(np.mean(b < 1e-6))

# =========================================================
# 6) MONTH-WISE METRICS (SAME FORMAT AS STGAT CSV)
# =========================================================
rows = []

for m in range(1, T):  # months 1..35
    yt = y[:, m]
    yp = arima_pred[:, m-1]

    rows.append({
        "YEAR_MONTH": months_all[m],
        "MONTH_INDEX": m,
        "MAE": MAE(yt, yp),
        "RMSE": RMSE(yt, yp),
        "MAPE": MAPE(yt, yp),
        "Accuracy@20": AccHR20(yt, yp),
        "Recall@20": Recall20(yt, yp),
        "ZeroRate": ZeroRate(yp),
        "SPLIT": ("TRAIN" if m <= 23 else ("VAL" if m <= 29 else "TEST"))
    })

arima_df = pd.DataFrame(rows)

# =========================================================
# 7) FINAL TEST SUMMARY
# =========================================================
test_df = arima_df[arima_df["SPLIT"] == "TEST"]

print("\n===== FINAL ARIMA METRICS (TEST AVG) =====")
for c in ["MAE","RMSE","MAPE","Accuracy@20","Recall@20","ZeroRate"]:
    print(f"{c:12s}: {test_df[c].mean():.6f}")

best_row = arima_df.loc[arima_df["MAE"].idxmin()]
print("\n===== BEST MONTH (ARIMA) =====")
for k, v in best_row.items():
    print(f"{k:14s}: {v}")

# =========================================================
# 8) SAVE CSV
# =========================================================
out_path = "/content/drive/MyDrive/Upstream/ARIMA_monthwise_metrics_36months.csv"
arima_df.to_csv(out_path, index=False)
print("\nSaved CSV:", out_path)





